### PR TITLE
Don't assume gcc.

### PR DESCRIPTION
**Pull request by djberg96**
This lets things work with Visual Studio, the Sun Studio compiler and so on. :)

### CODE REVIEW

**Comment by YorickPeterse** [comment]
eh, it didn't expect gcc in the first place, while it now _only_ adds the flags for gcc (and not clang and everything else). Is Visual Studio so braindead that it doesn't support `-Wall` and such? If so a better way would be to _not_ add the flags for just visual studio, instead of only adding it for gcc.

**Comment by djberg96** [comment]
I'm not sure I follow. With my patch it only adds the flags if gcc.

Visual Studio actually does support -Wall, but really you want -W3. However, the ruby-core team specifically overrides anything above -W2 (since Ruby 2.0 I think), so it wouldn't do any good anyway.

**Comment by djberg96** [comment]
The actual problem was the -Wextra switch, which isn't supported by Visual Studio. I doubt other compilers support it, either.

**Comment by YorickPeterse** [comment]
> I'm not sure I follow. With my patch it only adds the flags if gcc.

That's exactly the problem, it _only_ adds the flags when gcc is used. While I'm not sure if MRI can be compiled with clang these days you _can_ compile Rubinius with it (it's actually recommended and my current default compiler for it).

> The actual problem was the -Wextra switch, which isn't supported by Visual Studio. I doubt other compilers support it, either.

clang and gcc support it just fine. If this is the only option not supported by visual studio it can be skipped in case of VS, but simply not adding any flags is a bit too much if you'd ask me.

**Comment by YorickPeterse** [comment]
Put it this way:

* Does VS support `-Wall` and `-Wpedantic`?
* What does `RbConfig::CONFIG['gcc']` report in case you're compiling with VS?

**Comment by djberg96** [comment]
It supports -Wall but not -Wpedantic. By other compilers, I meant the Sun Studio compiler and the HP-UX compiler. I don't know if those options are supported for those compilers.

RbConfig::CONFIG['GCC'] returns nil for a Ruby compiled with Visual Studio and "yes" for the one-click installer.

**Comment by YorickPeterse** [comment]
Errr woops, I meant `RbConfig::CONFIG['cc']`.

**Comment by djberg96** [comment]
RbConfig::CONFIG['CC'] # => "cl -nologo"

"cl" is the command line compiler name. The -nologo thing is just to make it shut up about copyright.

BTW, the analogue to -g for VS is "-Z7" for debugging symbols in an .obj file. Or you can use "-Zi" and it will generate a .pdb file instead. It looks like -Od is the equivalent of -O0.

**Comment by YorickPeterse** [comment]
Moving this over to https://github.com/YorickPeterse/ruby-ll/issues/14. I'll look into adjusting the extconf.rb as well.

**Comment by djberg96** [comment]
Ok, thanks. BTW, I think you want 'CC', not 'cc'.

**Comment by YorickPeterse** [comment]
@djberg96 Gah, you're right.

**Pull request closed without merging**
